// web/src/views/SkillUpload.vue
<template>
  <v-container style="max-width: 600px">
    <v-btn variant="text" prepend-icon="mdi-arrow-left" to="/skills" class="mb-4"> Back to Skills </v-btn>

    <h1 class="text-h4 font-weight-bold mb-6">Upload New Skill</h1>

    <v-card class="pa-6">
      <v-form @submit.prevent="handleUpload">
        <v-text-field
          v-model="name"
          label="Skill Name"
          placeholder="e.g., my-awesome-lib"
          prepend-inner-icon="mdi-tag"
          :disabled="uploading"
          class="mb-4"
        />

        <v-file-input
          v-model="selectedFile"
          label="Source Code (ZIP)"
          accept=".zip"
          prepend-icon="mdi-folder-zip"
          chips
          show-size
          :disabled="uploading"
          class="mb-4"
        >
          <template #selection="{ fileNames }">
            <v-chip v-for="fileName in fileNames" :key="fileName" variant="tonal" color="secondary" size="small">
              {{ fileName }}
            </v-chip>
          </template>
        </v-file-input>

        <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error = ''">
          {{ error }}
        </v-alert>

        <v-btn
          variant="tonal"
          color="secondary"
          size="large"
          block
          :disabled="!canUpload"
          :loading="uploading"
          type="submit"
        >
          <v-icon icon="mdi-upload" class="mr-2"></v-icon>
          Upload Skill
        </v-btn>
      </v-form>
    </v-card>

    <v-card v-if="uploading" class="mt-6 pa-6">
      <h3 class="text-h6 mb-4">Processing Status</h3>

      <div class="d-flex align-center gap-3">
        <v-progress-circular
          :indeterminate="stage < 5"
          :model-value="stageProgress"
          variant="tonal"
          color="secondary"
        ></v-progress-circular>

        <StageIndicator :stage="stage" />
      </div>

      <p class="text-caption text-muted mt-4">You can check the status later in the skill list</p>
    </v-card>
  </v-container>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { uploadSkill, subscribeSkillStatus } from '@/api/skill'
import StageIndicator from '@/components/StageIndicator.vue'

const router = useRouter()

const name = ref('')
const selectedFile = ref<File[] | null>(null)
const uploading = ref(false)
const error = ref('')
const stage = ref(1)

const canUpload = computed(() => {
  return name.value.trim() && selectedFile.value && selectedFile.value.length > 0
})

const stageProgress = computed(() => {
  return ((stage.value - 1) / 4) * 100
})

const handleUpload = async () => {
  if (!name.value || !selectedFile.value || selectedFile.value.length === 0) return

  error.value = ''
  uploading.value = true
  stage.value = 1

  const file = selectedFile.value[0]
  if (!file) return

  try {
    const result = await uploadSkill(name.value, file, () => {})

    stage.value = 2

    const unsubscribe = await subscribeSkillStatus(result.skill_id, (newStage, newName) => {
      stage.value = newStage

      if (newName === 'completed' || newName === 'failed') {
        unsubscribe()
        router.push(`/skills/${result.skill_id}`)
      }
    })
  } catch {
    error.value = 'Failed to upload skill'
    uploading.value = false
  }
}
</script>

// web/src/pages/SkillUpload.tsx
import { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { Upload, Loader2 } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { useSkillStore } from "@/stores"

const stageNames = [
  "Pending",
  "Uploading",
  "Processing",
  "Overview",
  "API Retrieval",
  "Completed",
  "Failed",
]

export default function SkillUploadPage() {
  const navigate = useNavigate()
  const { uploadSkill, subscribeStatus, skillStatus, loadSkills } =
    useSkillStore()

  const [name, setName] = useState("")
  const [file, setFile] = useState<File | null>(null)
  const [uploading, setUploading] = useState(false)
  const [skillId, setSkillId] = useState<string | null>(null)
  const [currentStatus, setCurrentStatus] = useState<{
    stage: number
    name: string
  } | null>(null)

  useEffect(() => {
    if (!skillId) return
    const unsub = subscribeStatus(skillId)
    return () => unsub()
  }, [skillId, subscribeStatus])

  useEffect(() => {
    setCurrentStatus(skillStatus)
  }, [skillStatus])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!name.trim() || !file) return

    setUploading(true)
    try {
      const id = await uploadSkill(name.trim(), file)
      setSkillId(id)
      toast.success("Upload started")
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Upload failed")
      setUploading(false)
    }
  }

  useEffect(() => {
    if (!uploading || !skillId) return
    const checkInterval = setInterval(async () => {
      const { useSkillStore: store } = await import("@/stores")
      const status = store.getState().skillStatus
      if (status) {
        setCurrentStatus(status)
        if (status.name === "completed" || status.name === "failed") {
          setUploading(false)
          clearInterval(checkInterval)
          if (status.name === "completed") {
            toast.success("Skill processed successfully")
            loadSkills()
            navigate("/skills")
          } else {
            toast.error("Skill processing failed")
          }
        }
      }
    }, 2000)
    return () => clearInterval(checkInterval)
  }, [uploading, skillId, loadSkills, navigate])

  const isProcessing = uploading && skillId

  return (
    <div className="container mx-auto max-w-md p-6">
      <Card>
        <CardHeader>
          <CardTitle>Upload Skill</CardTitle>
          <CardDescription>
            Upload a ZIP file containing your source code
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <Label htmlFor="name">Skill Name</Label>
              <Input
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="my-awesome-skill"
                disabled={isProcessing}
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="file">ZIP File</Label>
              <Input
                id="file"
                type="file"
                accept=".zip"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                disabled={isProcessing}
              />
            </div>

            {isProcessing && (
              <div className="flex flex-col gap-2 rounded-md bg-muted p-3">
                <div className="flex items-center justify-between text-sm">
                  <span>Processing...</span>
                  <span className="text-muted-foreground">
                    {currentStatus
                      ? stageNames[currentStatus.stage]
                      : "Initializing"}
                  </span>
                </div>
                <Progress
                  value={currentStatus?.name === "completed" ? 100 : 50}
                />
              </div>
            )}

            <Button
              type="submit"
              disabled={!name.trim() || !file || isProcessing}
            >
              {isProcessing ? (
                <>
                  <Loader2 className="mr-2 size-4 animate-spin" />
                  Processing...
                </>
              ) : (
                <>
                  <Upload className="mr-2 size-4" />
                  Upload
                </>
              )}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
