// web/src/views/SkillList.vue
<template>
  <v-container>
    <div class="d-flex justify-space-between align-center mb-6">
      <h1 class="text-h4 font-weight-bold">My Skills</h1>

      <v-btn color="secondary" prepend-icon="mdi-upload" to="/skills/upload"> Upload New Skill </v-btn>
    </div>

    <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error = ''">
      {{ error }}
    </v-alert>

    <div v-if="loading" class="d-flex justify-center py-12">
      <v-progress-circular indeterminate color="primary" size="64"></v-progress-circular>
    </div>

    <v-empty-state
      v-else-if="skills.length === 0"
      icon="mdi-brain"
      headline="No skills yet"
      text="Upload your first skill to get started."
    >
      <template #actions>
        <v-btn color="secondary" prepend-icon="mdi-upload" to="/skills/upload"> Upload Skill </v-btn>
      </template>
    </v-empty-state>

    <v-row v-else>
      <v-col v-for="skill in skills" :key="skill.id" cols="12" sm="6" md="4" lg="3">
        <v-card hover @click="goToDetail(skill.id)" class="skill-card h-100">
          <v-card-item>
            <template #prepend>
              <v-avatar color="secondary" variant="tonal">
                <v-icon icon="mdi-code-tags"></v-icon>
              </v-avatar>
            </template>

            <v-card-title>{{ skill.name }}</v-card-title>

            <v-card-subtitle>
              {{ formatDate(skill.created_at) }}
            </v-card-subtitle>
          </v-card-item>

          <v-card-actions>
            <StageIndicator :stage="skill.stage" />

            <v-spacer></v-spacer>

            <v-btn
              icon="mdi-delete"
              variant="text"
              color="error"
              size="small"
              @click.stop="handleDelete(skill.id)"
            ></v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { listSkills, deleteSkill } from '@/api/skill'
import StageIndicator from '@/components/StageIndicator.vue'

const router = useRouter()
const skills = ref<
  Array<{
    id: string
    name: string
    status: string
    stage: number
    created_at: string
  }>
>([])
const loading = ref(true)
const error = ref('')

const loadSkills = async () => {
  loading.value = true
  error.value = ''
  try {
    skills.value = await listSkills()
  } catch {
    error.value = 'Failed to load skills'
  } finally {
    loading.value = false
  }
}

const goToDetail = (id: string) => {
  router.push(`/skills/${id}`)
}

const handleDelete = async (id: string) => {
  if (!confirm('Are you sure you want to delete this skill?')) return
  try {
    await deleteSkill(id)
    await loadSkills()
  } catch {
    alert('Failed to delete skill')
  }
}

const formatDate = (dateStr: string) => {
  return new Date(dateStr).toLocaleDateString()
}

onMounted(loadSkills)
</script>

<style scoped>
.skill-card {
  transition:
    transform 0.2s,
    box-shadow 0.2s;
}

.skill-card:hover {
  transform: translateY(-4px);
}
</style>

// web/src/pages/SkillList.tsx
import { useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { Plus, Download, Trash2 } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { useSkillStore } from "@/stores"

const stageNames = [
  "Pending",
  "Uploading",
  "Processing",
  "Overview",
  "API Retrieval",
  "Completed",
  "Failed",
]

export default function SkillListPage() {
  const navigate = useNavigate()
  const { skills, isLoading, loadSkills, deleteSkill, downloadSkill } =
    useSkillStore()

  useEffect(() => {
    loadSkills()
  }, [loadSkills])

  const handleDelete = async (id: string) => {
    try {
      await deleteSkill(id)
      toast.success("Skill deleted")
    } catch {
      toast.error("Failed to delete skill")
    }
  }

  const handleDownload = async (id: string, name: string) => {
    try {
      await downloadSkill(id, name)
      toast.success("Download started")
    } catch {
      toast.error("Failed to download skill")
    }
  }

  return (
    <div className="h-full w-full">
      <div className="flex h-full flex-col">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">My Skills</h1>
          <Button onClick={() => navigate("/skills/upload")}>
            <Plus className="mr-2 size-4" />
            Upload Skill
          </Button>
        </div>

        <div className="flex flex-1">
          {isLoading ? (
            <div className="w-full space-y-4">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-32 w-full" />
              ))}
            </div>
          ) : skills.length === 0 ? (
            <div className="flex h-full w-full flex-col items-center justify-center">
              <p className="mb-4 text-muted-foreground">No skills yet</p>
              <Button onClick={() => navigate("/skills/upload")}>
                Upload your first skill
              </Button>
            </div>
          ) : (
            <div className="w-full space-y-4 pt-4">
              {skills.map((skill) => (
                <Card
                  key={skill.id}
                  className="cursor-pointer transition-colors hover:bg-accent/50"
                  onClick={() => navigate(`/skills/${skill.id}`)}
                >
                  <CardHeader className="flex flex-row items-center justify-between pb-2">
                    <div>
                      <CardTitle>{skill.name}</CardTitle>
                      <CardDescription>
                        {skill.description || "No description"}
                      </CardDescription>
                    </div>
                    <div className="flex items-center gap-2">
                      {skill.status === "completed" && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation()
                            handleDownload(skill.id, skill.name)
                          }}
                        >
                          <Download className="mr-1 size-4" />
                          Download
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={(e) => {
                          e.stopPropagation()
                          handleDelete(skill.id)
                        }}
                      >
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="flex items-center gap-2">
                      <Badge
                        variant={
                          skill.status === "completed"
                            ? "secondary"
                            : skill.status === "failed"
                              ? "destructive"
                              : "outline"
                        }
                      >
                        {stageNames[skill.stage] || skill.status}
                      </Badge>
                      <span className="text-xs text-muted-foreground">
                        Created{" "}
                        {new Date(skill.created_at).toLocaleDateString()}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
